/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GestionAsientosAutob;

import java.util.Date;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import Modelo.Poblacion;
import Modelo.Corridas;
import Modelo.Boletos;
import Controll.BoletosJpaController;
import Controll.CorridasJpaController;
import Controll.PoblacionJpaController;
import Modelo.ModeloTablaCorrida;
import Controll.EstrucuturaCorrida;
import Controll.AutobusJpaController;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;

/**
 *
 * @author manel
 */
public class GestionAsientosAutob extends javax.swing.JDialog {

    /**
     * Creates new form GestionAsientosAutob
     */
     EntityManagerFactory emf = Persistence.createEntityManagerFactory("ProyectoGestorAutoBusPU");
     CorridasJpaController cjp= new CorridasJpaController(emf);
     PoblacionJpaController pjp= new PoblacionJpaController(emf);
     AutobusJpaController ajp=new AutobusJpaController(emf);
     BoletosJpaController bpj=new BoletosJpaController(emf);
     List<Boletos> bol =new ArrayList<Boletos>();
     List<Boletos> vendidos =new ArrayList<Boletos>();

     public int fila=-1;
     public int asiento=0;
     public int cuantos=0;
     public int contar=0;
     int boletos=0;
    public GestionAsientosAutob(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Date date=new Date();
        jDateChooser1.setMinSelectableDate(date);
        origenDestino1.setCiudades(ciudades());
        jLabel6.setVisible(false);
        jComboBox1.setVisible(false);
        //iReservaAsiento1.setNumAsientos(40);   
          // iReservaAsiento1.setDistribucion("horizontal");
        
    }
     private String[] ciudades() {
         List <Poblacion> lp = pjp.findPoblacionEntities();
         String[] ciuds = new String[lp.size()];
          for(int c=0;c<ciuds.length;c++){
        ciuds[c]=lp.get(c).getNombre();
    }
    return ciuds;
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        origenDestino1 = new comod.OrigenDestino();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Seleccionar Ruta ");

        jLabel2.setText("Origen-Destino");

        jCheckBox1.setText("todos los viajes ");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha ");

        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(origenDestino1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jCheckBox1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel3)
                        .addGap(64, 64, 64)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(origenDestino1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(46, 46, 46))
        );

        jTabbedPane1.addTab("Inicio", jPanel1);

        jLabel4.setText("Lista de corridas ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Aceptar Corridas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jButton2)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Corridas", jPanel2);

        jLabel7.setText("Cuantos boletos desea");

        jButton4.setText("Aceptar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setText("Boleto que desea");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton3.setText("Continuar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Num_Corrida:           ");

        jLabel8.setText("Introdusca Nombre");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jButton4))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(140, 140, 140)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addGap(56, 56, 56)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton3)
                .addGap(75, 75, 75))
        );

        jTabbedPane1.addTab("AsignarPasaje", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Boleto", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cancelar", jPanel6);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Reserva", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()){
          List<Corridas> lc =cjp.findCorridasEntities();
          EstrucuturaCorrida eco= new EstrucuturaCorrida();
          ModeloTablaCorrida mtc = new ModeloTablaCorrida(eco,lc);
          jTable1.setModel(mtc);
        }else{
            if(origenDestino1.getOrigen()==null||origenDestino1.getDestino()==null||jDateChooser1.getDate()==null){
                JOptionPane.showMessageDialog(null,"por favor llene los requisitos");
            }else{
             EntityManager em = emf.createEntityManager();
             Query consultap =em.createNamedQuery("Poblacion.findByNombre");
             consultap.setParameter("nombre",origenDestino1.getOrigen());
             Poblacion p1= (Poblacion)consultap.getSingleResult();
             consultap.setParameter("nombre",origenDestino1.getDestino());
             Poblacion p2= (Poblacion)consultap.getSingleResult();
             Query consultaC=em.createNamedQuery("Corridas.findfechajorigenjdestino");
             consultaC.setParameter(1,jDateChooser1.getDate() );
             consultaC.setParameter(2,p1);
             consultaC.setParameter(3,p2);
             List <Corridas> lista =consultaC.getResultList();
             EstrucuturaCorrida eco= new EstrucuturaCorrida();
          ModeloTablaCorrida mtc = new ModeloTablaCorrida(eco,lista);
          jTable1.setModel(mtc);
            }
        }
        tablaCorrida();
    }//GEN-LAST:event_jButton1ActionPerformed
     public void tablaCorrida(){
        jTable1.addMouseListener(new MouseAdapter() 
   {
      public void mouseClicked(MouseEvent e)
      {
        fila = jTable1.rowAtPoint(e.getPoint());
        asiento= (int)jTable1.getValueAt(fila, 6); 
      }
   }); 
         jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTable1.setColumnSelectionAllowed(true);
     }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       int aux=0;
       boletos=boletos+1;
    
       if(contar==cuantos){
          JOptionPane.showMessageDialog(null,"son todos los boletos ");  
          /* Boletos bb=new Boletos();
            bb.setNumasineto(boletos);
            bb.setPasajero(jTextField2.getText());
            bpj.create(bb);
            vendidos.add(bb);*/
          for (int x=0;x<vendidos.size();x++){
            jPanel5.setLayout(new FlowLayout());
            JTextArea jt=new JTextArea(10,10);
            jt.setText("\n"+"Folio:"+vendidos.get(x).getFolio()+"\n"+"nombre pasajero"+vendidos.get(x).getPasajero()+"\n"+"asiento"+vendidos.get(x).getNumasineto());
            jPanel5.add(jt);   
          
        }
       }
       else  if(jTextField2.getText().equals("")||jTextField2.getText().equals(" ")){
           JOptionPane.showMessageDialog(null,"introduzca nombre por favor");
       }else{
              
           boletos=boletos+1;
        EntityManager em = emf.createEntityManager();
        Query consultap =em.createNamedQuery("Boletos.encuentrarepetido");
        consultap.setParameter(1, jTextField2.getText());
        List <Boletos> lista =consultap.getResultList();
       // Boletos b=bpj.findBoletos(boletos);
                                 for(int x=0;x<lista.size();x++){
                                    Corridas auxiliar =cjp.findCorridas(lista.get(x).getCorrida().getIdCorrida());
                                    if(auxiliar.getFecha()==lista.get(x).getCorrida().getFecha()){
                                    aux=aux+1;   
                                    }   
                                    }
        if(aux>0){
            JOptionPane.showMessageDialog(null, "este paseajero ya esta registrado eb otro viaje con la misma fech");
            // bb.setPasajero(jTextField2.getText());
            jTextField2.getText();
        }else{
            contar=contar+1;
             GridBagConstraints rt =new GridBagConstraints();
         GridBagLayout gb=new GridBagLayout();
      rt.anchor = GridBagConstraints.WEST;
      rt.fill= GridBagConstraints.VERTICAL;
     rt.gridwidth=1;
            //jPanel5.setLayout(null);
            Boletos bb=new Boletos();
            bb.setNumasineto(boletos);
            bb.setPasajero(jTextField2.getText());
            int encuentra=(int)jTable1.getValueAt(fila, 0);
              Corridas cor=cjp.findCorridas(encuentra);
            bb.setCorrida(cor);
            bpj.create(bb);
            vendidos.add(bb);
            //JTextArea jt=new JTextArea(10,10);
           // jt.setText("\n"+"Folio:"+bb.getFolio()+"\n"+"nombre pasajero"+jTextField2.getText()+"\n"+"asiento"+bb.getNumasineto());
          // jPanel5.add(jt,rt);
           
        }                       
       }
         
       /* for (int x=0;x<vendidos.size();x++){
            jPanel5.setLayout(new FlowLayout());
            JTextArea jt=new JTextArea(10,10);
            jt.setText("\n"+"Folio:"+vendidos.get(x).getFolio()+"\n"+"nombre pasajero"+vendidos.get(x).getPasajero()+"\n"+"asiento"+vendidos.get(x).getNumasineto());
            jPanel5.add(jt);
            
          
        }*/
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        tablaCorrida();
        if(fila<0){
            JOptionPane.showMessageDialog(null, "seleccione su viaje, por favor");
        }else{
           int encuentra=(int)jTable1.getValueAt(fila, 0);
              Corridas cor=cjp.findCorridas(encuentra);
               //jComboBox1.removeAllItems();
               /*Boletos b=new Boletos();
          for(int x=0;x<asiento;x++){
              
               
               b.setNumasineto(x+1);
              // jComboBox1.addItem(x+1);
               b.setCorrida(cor);
               bpj.create(b);
                bol.add(b);
                System.out.println(b.getFolio());
           }*/
          System.out.println(bol.size());
          jLabel5.setText("Num_Corridas:" +cor.getIdCorrida());
          combo();
        }
    }//GEN-LAST:event_jButton2ActionPerformed
   public void combo(){
       jComboBox1.addItemListener(
                new ItemListener() { // anonymous inner class
                    // handle JComboBox event
                    public void itemStateChanged(ItemEvent event) {
                       
                        if (event.getStateChange() == ItemEvent.SELECTED) {
                            contar=contar+1;
                            if(contar>cuantos){
                               JOptionPane.showMessageDialog(null, "son todos los boletos que usted pidio");
                               
                            }else{
                                String s=String.valueOf(jComboBox1.getSelectedItem());
                                int estes=Integer.parseInt(s);
                                
                                Boletos b=bpj.findBoletos(bol.get(estes).getFolio());
                               
                                
                               /* jTextField2.setText(" "); 
                                 b.setPasajero(jTextField2.getText());
                                 try {
                                    bpj.edit(b);
                                } catch (Exception ex) {
                                    Logger.getLogger(GestionAsientosAutob.class.getName()).log(Level.SEVERE, null, ex);
                                }*/
                                int aux=0;
                                EntityManager em = emf.createEntityManager();
                                Query consultap =em.createNamedQuery("Boletos.encuentrarepetido");
                                consultap.setParameter(1, jTextField2.getText());
                                 List <Boletos> lista =consultap.getResultList();
                                 for(int x=0;x<lista.size();x++){
                                    Corridas auxiliar =cjp.findCorridas(lista.get(x).getCorrida().getIdCorrida());
                                    if(auxiliar.getFecha()==b.getCorrida().getFecha()){
                                    aux=aux+1;   
                                    }    
                                    }
                                  if (aux>0){
                                     JOptionPane.showMessageDialog(null, "Este pasajero ya esta registardo en cotra corrida con esta misma fecha por favor eliga otra corrid");  
                                  }else{
                                 
                                  b.setPasajero(jTextField2.getText());
                                 try {
                                    bpj.edit(b);
                                } catch (Exception ex) {
                                    Logger.getLogger(GestionAsientosAutob.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                 // vendidos.add(b);
                                    
                               
                                
                                  }
                                
                            }
                         
                        }
                    }
                }
        );
   }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        cuantos=Integer.parseInt(jTextField1.getText());
        jTextField1.setEnabled(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionAsientosAutob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionAsientosAutob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionAsientosAutob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionAsientosAutob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionAsientosAutob dialog = new GestionAsientosAutob(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private comod.OrigenDestino origenDestino1;
    // End of variables declaration//GEN-END:variables
}
